services:
  sftp:
    build:
      context: ./sftp
    container_name: openssh-sftp
    environment:
      PORT_START: "22001"
      PORT_END: "22100"
      UID_BASE: "20000"
    ports:
      - "22001-22100:22001-22100"
    volumes:
      - ./clients:/config/clients
      - sftp_state:/config/state
      - sftp_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sftp_state:
  sftp_data:
